# Generated by Django 4.1.3 on 2023-01-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
