# Generated by Django 4.1.3 on 2022-12-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
