# Generated by Django 4.1.3 on 2022-12-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_status_orderitem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
