# Generated by Django 4.1.3 on 2022-12-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_orderitem_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='retailer',
        ),
    ]
