# Generated by Django 4.1.3 on 2023-01-02 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0015_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('open_time', models.CharField(max_length=300)),
                ('close_time', models.CharField(max_length=300)),
                ('address', models.TextField(max_length=10000)),
                ('account_type', models.CharField(max_length=300)),
                ('account_number', models.CharField(max_length=300)),
                ('bank_name', models.CharField(max_length=300)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
