# Generated by Django 4.1.3 on 2023-01-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_retailer_delete_bankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
